### ISSUE TITLE
many tests fail when ERRBIT_USER_HAS_USERNAME=true

### ISSUE THREAD

**Issue by mfrederickson** [errbit/errbit#1049]
I had this set in my dev environment and ran `rake spec` and had a couple hundred failures... almost gave me a heart attack ;-) Then I changed it back to false and reran the tests and only had a couple failures (of my own making).  Is this something that should be avoided, or fixed?

**Comment by stevecrozz** [comment]
Yeah. I think we should do something with this. I did recently add this commit: 
https://github.com/errbit/errbit/commit/d2045f744491c273ef66ba057370d03ad4d76ed7

There's probably lots of inputs that need to be set a certain way to run reliably. This was my first idea for setting them:
https://github.com/errbit/errbit/blob/v0.6.0/spec/spec_helper.rb#L1

But we could also go full-on dotenv and have a .env.test file instead. Since this issue is about a specific input though, I'm thinking we should keep it simple and solve this one specifically and if something like it comes up again we can think about a more general solution.
