### ISSUE TITLE
Send notification in background jobs

### ISSUE THREAD

**Issue by quexpl** [errbit/errbit#1084]
Errbit needs send notifications in background process, there is no reason to wait until notifications are sent, it only slows down errbit client. Let's start disquss about this.
Referenced PR: #834 #1082

**Comment by stevecrozz** [comment]
This is a great idea. There are of course tons of ways to accomplish this. In my mind, the ideal solution would be something that is very simple and has no additional deployment dependencies. It would be great if the existing puma master process could start one or more background threads for async notifications and process them without blocking the main web threads. That could likely be done in config/puma.rb

I haven't done a ton of investigation into this, but what I'm imagining is a system where instead of sending notifications in the middle of web requests, we'd persist jobs in a mongodb collection to be processed independently by another thread.

One option would be to use Active Job and sucker_punch by default. That would potentially leave the door open for us to use something more complex down the road. If we wanted to replace sucker_punch with sidekiq for instance that would supposedly be easy if we were using Active Job.

Just some ideas to get the conversation started.

**Comment by quexpl** [comment]
Well i think that solution proposed by @Strnadj in Strnadj@4f389a5 is great. By defautl all ActiveJobs runs immediately (by inlineAdapter), but when user set ENV['QUEUE_ADAPTER'] jobs start running in backgound.

**Comment by stevecrozz** [comment]
Yeah. Maybe that would be a good first step, to use active job to manage notifications with no specific support for a particular adapter.
