### ISSUE TITLE
Combatible with Airbrake 5?

### ISSUE THREAD

**Issue by glampr** [errbit/errbit#1087]
Is the latest gem compatible with the new Airbrake v5 (released 18th December 2015)?

**Comment by stevecrozz** [comment]
Should be. Are you finding any problems?

**Comment by gjastrab** [comment]
I had an error when I had tried setting up a new test staging environment running inside Docker with the (I believe) 0.6.1 tag. I think i was properly on that tag (and not master), but I was in a bind, so I just rolled back to 0.6.0 to get up and running quickly and it worked for me then.

On 0.6.1 errbit had told me to set my app's Gemfile to use airbrake with `'~> 5.0'`, however when the app tried to report errors if I recall I think the issue was that errbit 0.6.1 didn't have the proper routes setup to respond to the new way of identifying the app (using `project_id` and `project_key` instead of just an `api_key`).

Don't quote me on that because I didn't get to re-test this more thoroughly yet but perhaps investigate if that is the issue?

**Comment by mattberther** [comment]
I believe you need to update the initializer to pass along the project_id (which is the application id from the URL) and also change api_key to project_key. 

https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md

**Comment by gjastrab** [comment]
Yep, I had done that in the app, so the app was calling my errbit with that project_id & project_key parameters but errbit was throwing a Route not found error - it seemingly didn't know how to respond to the v5 style Airbrake URLs.

**Comment by leckylao** [comment]
Agreed with @gjastrab , I have the same issue here and I can confirm that it doesn't compatible with Airbrake 5. Here's the error:

`ActionController::RoutingError (No route matches [POST] "/api/v4/projects/1/deploys")`

And when you run rake routes from errbit there's only route for /api/v3 and no route for /api/v4

From Airbrake5 it adds Airbrake-ruby as dependency. And you can see since Airbrake-ruby v1 the create_deploy method's endpoint is using /api/v4. As shows here

https://github.com/airbrake/airbrake-ruby/blob/v1.0.0/lib/airbrake-ruby/notifier.rb#L100

Therefore, in order to support Airbrake5, will need to add support for the route /api/v4

**Comment by stevecrozz** [comment]
@leckylao: errbit doesn't support deploy tracking any more, but the rest of this does seem to be a problem we need to address

**Comment by leckylao** [comment]
@stevecrozz Thanks for the reply. That was a good feature. Pity to hear it's gone..... It would be good to highlight that in the README.

**Comment by stevecrozz** [comment]
@leckylao Yeah I know there were a few people who used that feature. If you're interested in the rationale, you can read a little more at: https://github.com/errbit/errbit/issues/913

**Comment by nofxx** [comment]
Albeit it works, errors do get into errbit nicely, the gem is kinda confused by the return:

```
**Airbrake: unexpected code (200). Body: {"notice":{"id":"5769c5926c61620ca40019ef"}}
```

Maybe it's something to do with expecting a Integer project ID too...

**Comment by stevecrozz** [comment]
@nofxx Are you using v0.6.1?

This controller is supposed to return status code of 201: https://github.com/errbit/errbit/blob/v0.6.1/app/controllers/api/v3/notices_controller.rb#L21

**Comment by nofxx** [comment]
@stevecrozz my bad! was on 0.3.0! No error on errbit 0.6.1!
Locking airbrake-ruby on 1.3.2, because of the `to_i` issue mentioned.
For those reading only this ^

**Comment by lucianosousa** [comment]
I think this issue can be closed, isn't?
