### ISSUE TITLE
No documentation for running errbit using HTTPS

### ISSUE THREAD

**Issue by ccouzens** [errbit/errbit#1137]
There is no documentation for running errbit using https.

By reading the puma documentation, I figured out it could be done by running:

```bash
puma -b "ssl://0.0.0.0:443?key=/certificates/server.key&cert=/certificates/server.crt" -C config/puma.default.rb
```

Would you accept a pull request to add this to the documentation?

Additionally, would you accept a pull request to create an alternative docker image that serves using https?

**Comment by stevecrozz** [comment]
Formerly, we've been doing HTTPS with a separate front end web server to handle the TLS stuff, but if puma can do it, maybe that's just fine for small errbit deployments. A good place for that info would be https://github.com/errbit/errbit/blob/master/docs/deployment.md .

I don't think this would require a separate docker image, although we could explore that if you think it does. Docker users should be able to mount key and cert files onto the Docker container's filesystem and reference them with something like:
```bash
docker run \
  -e "RACK_ENV=production" \
  -e "MONGO_URL=mongodb://my-mongo-host" \
  -v /certificates /host/certificates/path \
  errbit/errbit:latest \
  bundle exec puma -b "ssl://0.0.0.0:443?key=/certificates/server.key&cert=/certificates/server.crt" -C config/puma.default.rb
```

For docker docs, there's probably more value in documenting that people can provide their own arguments to puma (in general) rather than making it all about TLS. But of course, one great example of that is exactly what you're doing by adding a TLS binding and I think there's room in the docs for an example like this in the Docker section: https://github.com/errbit/errbit/blob/master/docs/deployment/docker.md

Does that make sense? I'd like to focus on the flexibility available in general, but I think your example would make for a nice illustration of that.

**Comment by stevecrozz** [comment]
Resolved with https://github.com/errbit/errbit/issues/1139
