### ISSUE TITLE
Errbit::VERSION does not match latest release tag

### ISSUE THREAD

**Issue by floehopper** [errbit/errbit#1197]
[`Errbit::VERSION` is "0.6.0"](https://github.com/errbit/errbit/blob/d75676500bbf87a56a81f36c5b15caf4f669c6ef/lib/errbit/version.rb#L2), but the latest release tag is "v0.6.1" which tags [this commit](https://github.com/errbit/errbit/commit/a0929bc86efafc3536b97c818b540d8173842326).

Also there is no entry in [`CHANGELOG.md`](https://github.com/errbit/errbit/blob/d75676500bbf87a56a81f36c5b15caf4f669c6ef/CHANGELOG.md) for the v0.6.1 release.

**Comment by stevecrozz** [comment]
Good point about the mismatched version constant. I suppose we should update that.

Regarding the changelog, I'm thinking of getting rid of it and updating the contribution guidelines because I've taken to using a combination of milestones such as https://github.com/errbit/errbit/milestone/11 and the regular commit log. I found that I had been copy pasting lines out of the commit log into the change log and it began to feel pointless. My thought is it would be better to spend that time keeping the commit log nice and tidy.

Since you're here, do you have any opinion on all that?

**Comment by floehopper** [comment]
As a user of the software, I'd definitely prefer for it to be easy to see what's changed between versions, but obviously that has to be balanced against how much time you (and any other maintainers?) have for maintaining the CHANGELOG. I think there's sometimes value in having a summary of the changes rather than just the detailed commit note subject lines. But in the end, I think it's your call!

BTW Thanks for all your work on the project!

**Comment by stevecrozz** [comment]
This makes sense. We've been using github milestones for tracking changes over time so I went ahead and created a 0.6.1 milestone and populated it with the items that made it into that release. Thanks for pointing out this issue @floehopper !

**Comment by floehopper** [comment]
👍

**Comment by floehopper** [comment]
@stevecrozz: Are you planning to update the `VERSION` constant too?

**Comment by stevecrozz** [comment]
Ah yeah I suppose I should. I'm also going to create a RELEASE.md file so I stop forgetting to do this stuff.

**Comment by floehopper** [comment]
👍
