### ISSUE TITLE
allow issue tracker gems to provide a template for the remote issue body

### ISSUE THREAD

**Issue by stevecrozz-** [errbit/errbit#783]
As of #774, issue trackers can only have one template and that is not necessarily suitable for all issue trackers. Errbit should allow issue tracker plugins to provide their own template.

**Comment by stevecrozz** [comment]
This one is ready to start. Now that #785 is done, it may make sense to add the ability for issue trackers to specify a default template to use (md, txt, etc). I think we still need a way for plugins to define the entire template, but the default template should work for most trackers since we now have multiple formats.

Here's one idea for an interface that should work:
IssueTracker#body_template **optional** if this method exists, it should return an ERB template to render, or a symbol. If it is a symbol it should be one of the available default template formats such as txt or md (like the ones I created in #774). If this method is unimplemented, we'll render the default template in markdown format.

**Comment by stevecrozz** [comment]
@arthurnn Added PR #840 which should give us what we want here
