### ISSUE TITLE
airbrake v3 api compatibility

### ISSUE THREAD

**Issue by stevecrozz** [errbit/errbit#803]
Errbit only supports the Airbrake v2 API. We should add support for v3 because some clients only support the newer version.

**Comment by shivanibhanwal** [comment]
As per the airbrake-js api call it will be making a call to API/V3 and also in the URL it will be passing the `Project_id` and `api_key` as well. However in the earlier version of the errbit API/V2 "Notices api" 
request does not expect `Project_id` and `apikey`
     
    /api/v3/projects/[PROJECT_ID]/notices?key=[API_KEY]

To support airbrake-js I am thinking to utilise errBit `API Key` and may be `app_id`

**Comment by stevecrozz** [comment]
Sounds like a good call to me. We don't have a project id, but we do have an app id like you said. Let's go with that.

**Comment by shivanibhanwal** [comment]
Ok cool I have started working on it but see that earlier api's were handled little differently.
Specially the way V1 and V2 has been created. I will post more details on that later

But I ran into an issue related to cross-origin thing, whenever we are sending a call from ember side via airbrake-js it is sending request with OPTIONS method and that is due to CORS issue
I have created a issue on airbrake-js https://github.com/airbrake/airbrake-js/issues/122
If you have any suggestions please do tell me.

**Comment by stevecrozz-** [comment]
I think this just depends on where you're seving up airbrake-js. If its not on the same domain as your errbit, then the same origin policy will prevent you from sending the request. It looks like that's what's happening to you and if you want to allow it, we'll have to enable CORS for this new API.

**Comment by shivanibhanwal** [comment]
@stevecrozz I will explain my case here

We have a client app which runs on different domain and errbit runs on a different domain.
e.g. on my local these are running on different ports
     App is running on localhost:3000
     Errbit is running on localhost:5000

So when localhost:3000 sends request to localhost:5000 it receives it as OPTIONS method type instead of POST request. As per the airbrake-js they have created this request with POST method.
However due to cross origin issue, it is not accepted by ERRBIT 
For reference -http://stackoverflow.com/questions/8153832/xmlhttprequest-changes-post-to-option

So in such case where ERRBIT is running on different domain and if it has to accept the request from some other domain, should not we add cyu/rack-cors gem which provides us a way to configure the cross origin requests?
Also it can be made optional, By default we will keep it commented and if anyone needs CORS support they will uncomment the cofiguration

e.g.

    config.middleware.insert_before 0, "Rack::Cors" do
      allow do
        origins '*'
        resource '*', :headers => :any, :methods => [:get, :post, :options]
      end
    end

**Comment by shivanibhanwal** [comment]
@stevecrozz I did this change  on Errbit as mentioned above in my comment and it works perfectly and supporting the request now

**Comment by shivanibhanwal** [comment]
@stevecrozz I have one question around the data parsing.
- We have a different payload for the Airbrake-js and I think for the notifier it was totally different and based on that Error_report table is designed.
However airbrake.js payload looks like this - https://gist.github.com/d740fa7770a0f44893e9.git

Right now I am doing data parsing so that it can be saved in the errbit ErrorReport
I noticed a class lib/hoptoad which should airbrake right as it was earlier named as "hoptoad"?
So can I use this same lib for the parsing purpose as that data is also from airbrake-js.

**Comment by stevecrozz** [comment]
Yes, I think we should use CORS, but we should only enable it for this one API path right now and the allowed origins should probably be configurable via environment variable (CORS_ALLOW_ORIGINS="originone.com origintwo.com" or something like that. I think by default we can have leave CORS enabled for this APIv3 path and let's just leave it open to all domains by default. Does anyone object to that?

I'm not sure what you're talking about with lib/hoptoad though. I don't think that has anything to do with this. We just need to take the incoming JSON document (whose format is described by this JSON schema https://gist.github.com/vmihailenco/14b538ccfb127eaea51e) and transform it into something our mongo schema can accept. Are there some incompatibilities? If you're just asking about where to put the code, then how about something like lib/airbrake_v3_notice_parser.rb?

**Comment by shivanibhanwal** [comment]
Yes there are some incompatibilities and json comes as https://gist.github.com/d740fa7770a0f44893e9 in my case, which is different the the notifier.js json.

Thank you for the inputs will do changes and let you know. 
About lib/hoptoad I wanted to understand for what we are using that lib?

**Comment by stevecrozz** [comment]
FYI: It looks like @ronin has put in a PR for this feature: https://github.com/errbit/errbit/pull/808

**Comment by shivanibhanwal** [comment]
Oh really. I was working on this. I will check this out in my project right away.

**Comment by shivanibhanwal** [comment]
@stevecrozz change which @ronin has committed work perfectly with the airbrake-js just tested with my project. Are you planning to merge this PR soon?

**Comment by stevecrozz** [comment]
This should be resolved now that we merged #808
