### ISSUE TITLE
Unexpected Behavior with ENV in Gemfile

### ISSUE THREAD

**Issue by mtmcfarl** [errbit/errbit#838]
I recently got a fresh clone of errbit and put it on my dev machine and cd into the directory after which I was greeted with:

``` Unknown ruby interpreter version (do not know how to handle): ENV[GEMFILE_RUBY_VERSION]ifENV[GEMFILE_RUBY_VERSION].```

I use rvm and do not have that environment variable set.  When I switch the conditional in the Gemfile to be block based instead of inline, the warning / message seems to go away.

Thoughts?

**Comment by stevecrozz** [comment]
Looks like RVM attempts to figure out which version of ruby you want to use by parsing it out of the Gemfile with some dirty black shell magic: https://github.com/wayneeseguin/rvm/blob/f01bfa7959cca7188caf59b094cfee33e0e1503c/scripts/functions/rvmrc_project#L133-L137

You can see exactly what's happening when you run it by hand:
```bash
$ echo "ruby ENV['GEMFILE_RUBY_VERSION'] if ENV['GEMFILE_RUBY_VERSION']" | command tr -d '\r' | sed -n "s/[[:space:]]+rescue[[:space:]]+nil$//; /^\s*ruby[[:space:](]/ {s/^\s*ruby//; s/[[:space:]()'\"]//g; p;}"
ENV[GEMFILE_RUBY_VERSION]ifENV[GEMFILE_RUBY_VERSION]
```
Splitting it over multiple lines isn't a great fix because the result is still wrong, even if RVM doesn't choke:
```bash
$ echo $'if ENV["GEMFILE_RUBY_VERSION"]\n  ruby ENV["GEMFILE_RUBY_VERSION"]\nend' | command tr -d '\r' | sed -n "s/[[:space:]]+rescue[[:space:]]+nil$//; /^\s*ruby[[:space:](]/ {s/^\s*ruby//; s/[[:space:]()'\"]//g; p;}"
ENV[GEMFILE_RUBY_VERSION]
```

This seems to me like a bug in RVM. We can potentially work around it with something like:
```ruby
send(:ruby, ENV['GEMFILE_RUBY_VERSION']) if ENV['GEMFILE_RUBY_VERSION']
```

You're welcome to give that a try and we can make that change, but it's not awesome that we're essentially relying on this shell scripting snippet in order to support RVM. Maybe you can report this as a bug with them...

**Comment by stevecrozz** [comment]
Maybe a better solution is to remove this line entirely, which was only added to support heroku. Heroku has an alternative way for specifying the ruby version: https://devcenter.heroku.com/articles/ruby-versions#specifying-a-ruby-version-via-the-environment

We just need to verify that it works and we can make that change.

**Comment by mtmcfarl** [comment]
I'd just assume to remove the line in the Gemfile.

**Comment by stevecrozz** [comment]
Ugh, I was mistaken. We can't remove it and still support multiple ruby versions and also support rvm. I'm going to test my hack that I wrote in my last comment and I'll send a message to Heroku about this also because this is the recommendation they have in their own docs and it seems to be incompatible with rvm.

**Comment by stevecrozz** [comment]
@mtmcfarl Would you mind testing this "fix" to see if it keeps RVM from complaining?
https://github.com/stevecrozz/errbit/tree/gemfile_ruby_version

**Comment by mtmcfarl** [comment]
That “fix” seem to have worked for me with rvm.
