### ISSUE TITLE
Unclear need/usage of cached last_deploy_at field in Problems

### ISSUE THREAD

**Issue by jaronkk** [errbit/errbit#912]
I'm trying to resolve an issue on our local Errbit installation, and I am trying to understand the intent of the last_deploy_at field?  

Right now it looks like every time a deploy is done, all Problem records for the app have their last_deploy_at set to the created_at timestamp of the most recent deploy for their app/environment. See: https://github.com/errbit/errbit/blob/master/app/models/problem.rb#L134-L136

This means that if I have a single environment for an application, the deploy timestamp for all of the Problem records will be exactly the same. The last_deploy_at is used as a sortable field in the problem list under the header "Deploy".  Based on that name I would assume the timestamp should represent the timestamp of the deploy when the problem was last encountered.  As it is, even problems that have been resolved will have their deploy timestamp updated on every deploy.

The reason I'm trying to understand the intention of the field is that we ended up with a large number of background jobs failing and now have 45,000+ Problem records for an app.  Errbit deals with that number pretty well for the most part, but the problem occurs when a new Deploy record is created.  In the deploy model it calls store_cached_attributes_on_problems as an after_create hook, and that method proceeds to update every Problem related to the app: https://github.com/errbit/errbit/blob/master/app/models/deploy.rb#L35-L37

The store_cached_attributes_on_problems call eventually times out, resulting in an error for every deploy notification, in addition to it taking so long.

**Comment by stevecrozz** [comment]
The whole deployment tracking feature has been inadequate for my needs because I generally have more than one version of my apps deployed at a single time and so I can't use it. It would be much better to supply version information in the error notification (as the airbrake api allows) so we can know which errors were triggered from which versions of an app, rather than having to intuit which version belongs to which error based on when a 'deploy' happened.

It sounds like you are tracking deploys with errbit though, and I'd be interested to see why you do it and if you would miss this feature if it went away.

**Comment by jaronkk** [comment]
We're not using the deploy tracking for anything in particular.  We enabled it since it was a simple two-line change to our existing deploy script, but we have existing methods for tracking deploys.

With the current implement it doesn't seem like anything in Problem#cache_app_attributes is really needed.

**Comment by stevecrozz** [comment]
@jaronkk #913 Removal of the deployment tracking feature is on the roadmap.
