### ISSUE TITLE
Remove dependency on MongoDB

### ISSUE THREAD

**Issue by moubry** [errbit/errbit#993]
MongoDB is licensed under AGPL, so its use (in any capacity) is strictly banned by many companies [such as Google](http://www.theregister.co.uk/2011/03/31/google_on_open_source_licenses/). There is a commercial license available for MongoDB, but it’s pretty expensive.

Since Errbit’s implicit goal is to be a free alternative to Airbrake—its use of MongoDB may be in-conflict with that goal, since Mongo can be costly for many people to run.

I’m not very familiar with the nuances of different licenses, so please feel free to correct any misunderstandings I may have.

**Comment by moubry** [comment]
This pull request to use Postgres would work: https://github.com/errbit/errbit/pull/623.

The rationale for not merging that pull request is that it didn't offer a big enough benefit. I'd just like to raise licensing of MongoDB as an additional reason for switching.

**Comment by stevecrozz** [comment]
I have no strong attachment to mongo aside from not wanting to do the work of porting errbit to another technology. PR #623 could maybe be salvaged in parts, but it would need a lot of work to merge cleanly with the current errbit.

@moubry Do you work at a company where you cannot use errbit because of mongo licensing issues?

**Comment by arrowcircle** [comment]
Finally! Mongo is strange, https://www.linkedin.com/pulse/mongodb-32-now-powered-postgresql-john-de-goes

**Comment by stevecrozz** [comment]
That's quite a stinging article. Thanks for sharing @arrowcircle.

It seems clear enough that this community would like to move to postgres and ditch mongo. I'm still not opposed to the idea, but personally, I can't commit the time necessary to make this change.

**Comment by stevecrozz** [comment]
I'm closing this because it's not something I plan to put on the backlog until we have a more full discussion about it. The licensing argument could be a good one, but I would like to here from someone (preferably multiple people) who is definitely affected by it. If that's you, let's take it to the mailing list and/or gitter and think it through together.
